# Generated by Django 5.1.5 on 2025-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravakit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='sport_type',
            field=models.CharField(choices=[('AlpineSki', 'Alpine Ski'), ('BackcountrySki', 'Backcountry Ski'), ('Badminton', 'Badminton'), ('Canoeing', 'Canoeing'), ('Crossfit', 'Crossfit'), ('EBikeRide', 'E-Bike Ride'), ('Elliptical', 'Elliptical'), ('EMountainBikeRide', 'E-Mountain Bike Ride'), ('Golf', 'Golf'), ('GravelRide', 'Gravel Ride'), ('Handcycle', 'Handcycle'), ('HighIntensityIntervalTraining', 'High-Intensity Interval Training'), ('Hike', 'Hike'), ('IceSkate', 'Ice Skate'), ('InlineSkate', 'Inline Skate'), ('Kayaking', 'Kayaking'), ('Kitesurf', 'Kitesurf'), ('MountainBikeRide', 'Mountain Bike Ride'), ('NordicSki', 'Nordic Ski'), ('Pickleball', 'Pickleball'), ('Pilates', 'Pilates'), ('Racquetball', 'Racquetball'), ('Ride', 'Ride'), ('RockClimbing', 'Rock Climbing'), ('RollerSki', 'Roller Ski'), ('Rowing', 'Rowing'), ('Run', 'Run'), ('Sail', 'Sail'), ('Skateboard', 'Skateboard'), ('Snowboard', 'Snowboard'), ('Snowshoe', 'Snowshoe'), ('Soccer', 'Soccer'), ('Squash', 'Squash'), ('StairStepper', 'Stair Stepper'), ('StandUpPaddling', 'Stand Up Paddling'), ('Surfing', 'Surfing'), ('Swim', 'Swim'), ('TableTennis', 'Table Tennis'), ('Tennis', 'Tennis'), ('TrailRun', 'Trail Run'), ('Velomobile', 'Velomobile'), ('VirtualRide', 'Virtual Ride'), ('VirtualRow', 'Virtual Row'), ('VirtualRun', 'Virtual Run'), ('Walk', 'Walk'), ('WeightTraining', 'Weight Training'), ('Wheelchair', 'Wheelchair'), ('Windsurf', 'Windsurf'), ('Workout', 'Workout'), ('Yoga', 'Yoga')], default='', max_length=29, verbose_name='sport type'),
            preserve_default=False,
        ),
    ]
