# Generated by Django 5.1.5 on 2025-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravakit', '0002_alter_activity_options_activity_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='distance'),
            preserve_default=False,
        ),
    ]
