# Generated by Django 6.0.2 on 2026-07-01 13:29

from django.db import migrations, models


def forwards(apps, schema_editor):
    # Backfill the new calories column from the retained Strava JSON payload.
    # calories is a DetailedActivity-only field, sent as a whole-number float.
    Activity = apps.get_model("stravakit", "Activity")
    batch = []
    for a in Activity.objects.all().iterator():
        calories = (a.json or {}).get("calories")
        a.calories = round(calories) if calories is not None else None
        batch.append(a)
    if batch:
        Activity.objects.bulk_update(batch, ["calories"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('stravakit', '0004_promote_json_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'get_latest_by': 'start_date', 'ordering': ('-start_date',), 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='calories'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
