# Generated by Django 6.0.2 on 2026-07-01 13:37

from django.db import migrations, models


def forwards(apps, schema_editor):
    # Backfill the promoted social/achievement counts from the retained Strava JSON.
    Activity = apps.get_model("stravakit", "Activity")
    batch = []
    for a in Activity.objects.all().iterator():
        j = a.json or {}
        a.comment_count = j.get("comment_count", 0) or 0
        a.pr_count = j.get("pr_count", 0) or 0
        a.achievement_count = j.get("achievement_count", 0) or 0
        batch.append(a)
    if batch:
        Activity.objects.bulk_update(
            batch, ["comment_count", "pr_count", "achievement_count"], batch_size=500
        )


class Migration(migrations.Migration):

    dependencies = [
        ('stravakit', '0005_alter_activity_options_activity_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='achievement_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='achievements'),
        ),
        migrations.AddField(
            model_name='activity',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='activity',
            name='pr_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='PRs'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
