# Generated by Django 4.2.28 on 2026-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravakit', '0007_activity_detailed_activity_polyline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default='', max_length=50, verbose_name='first name')),
                ('lastname', models.CharField(blank=True, default='', max_length=50, verbose_name='last name')),
                ('profile', models.URLField(blank=True, default='', max_length=500, verbose_name='avatar URL')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='city')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='country')),
                ('follower_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='followers')),
                ('friend_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='following')),
                ('json', models.JSONField()),
            ],
            options={
                'verbose_name': 'athlete',
                'verbose_name_plural': 'athletes',
            },
        ),
    ]
