# Generated by Django 4.2.28 on 2026-07-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stravakit', '0008_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='athlete',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='stravakit.athlete'),
        ),
        migrations.AddField(
            model_name='gear',
            name='athlete',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gear', to='stravakit.athlete'),
        ),
    ]
