# Generated by Django 6.0.2 on 2026-07-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravakit', '0012_activity_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last synced at'),
        ),
    ]
