from django.db import models
from django.utils.translation import gettext_lazy as _


class SportType(models.TextChoices):
  ALPINE_SKI = "AlpineSki", _("Alpine Ski")
  BACKCOUNTRY_SKI = "BackcountrySki", _("Backcountry Ski")
  BADMINTON = "Badminton", _("Badminton")
  CANOEING = "Canoeing", _("Canoeing")
  CROSSFIT = "Crossfit", _("Crossfit")
  E_BIKE_RIDE = "EBikeRide", _("E-Bike Ride")
  ELLIPTICAL = "Elliptical", _("Elliptical")
  E_MOUNTAIN_BIKE_RIDE = "EMountainBikeRide", _("E-Mountain Bike Ride")
  GOLF = "Golf", _("Golf")
  GRAVEL_RIDE = "GravelRide", _("Gravel Ride")
  HANDCYCLE = "Handcycle", _("Handcycle")
  HIIT = "HighIntensityIntervalTraining", _("High-Intensity Interval Training")
  HIKE = "Hike", _("Hike")
  ICE_SKATE = "IceSkate", _("Ice Skate")
  INLINE_SKATE = "InlineSkate", _("Inline Skate")
  KAYAKING = "Kayaking", _("Kayaking")
  KITESURF = "Kitesurf", _("Kitesurf")
  MOUNTAIN_BIKE_RIDE = "MountainBikeRide", _("Mountain Bike Ride")
  NORDIC_SKI = "NordicSki", _("Nordic Ski")
  PICKLEBALL = "Pickleball", _("Pickleball")
  PILATES = "Pilates", _("Pilates")
  RACQUETBALL = "Racquetball", _("Racquetball")
  RIDE = "Ride", _("Ride")
  ROCK_CLIMBING = "RockClimbing", _("Rock Climbing")
  ROLLER_SKI = "RollerSki", _("Roller Ski")
  ROWING = "Rowing", _("Rowing")
  RUN = "Run", _("Run")
  SAIL = "Sail", _("Sail")
  SKATEBOARD = "Skateboard", _("Skateboard")
  SNOWBOARD = "Snowboard", _("Snowboard")
  SNOWSHOE = "Snowshoe", _("Snowshoe")
  SOCCER = "Soccer", _("Soccer")
  SQUASH = "Squash", _("Squash")
  STAIR_STEPPER = "StairStepper", _("Stair Stepper")
  STAND_UP_PADDLING = "StandUpPaddling", _("Stand Up Paddling")
  SURFING = "Surfing", _("Surfing")
  SWIM = "Swim", _("Swim")
  TABLE_TENNIS = "TableTennis", _("Table Tennis")
  TENNIS = "Tennis", _("Tennis")
  TRAIL_RUN = "TrailRun", _("Trail Run")
  VELOMOBILE = "Velomobile", _("Velomobile")
  VIRTUAL_RIDE = "VirtualRide", _("Virtual Ride")
  VIRTUAL_ROW = "VirtualRow", _("Virtual Row")
  VIRTUAL_RUN = "VirtualRun", _("Virtual Run")
  WALK = "Walk", _("Walk")
  WEIGHT_TRAINING = "WeightTraining", _("Weight Training")
  WHEELCHAIR = "Wheelchair", _("Wheelchair")
  WINDSURF = "Windsurf", _("Windsurf")
  WORKOUT = "Workout", _("Workout")
  YOGA = "Yoga", _("Yoga")
